FROM golang:1.24-alpine

RUN apk add --no-cache git ca-certificates bash && update-ca-certificates

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download


COPY . .

ENV CDC_GATEWAY_CONFIG=/config/config.yaml
ENV CDC_GATEWAY_GRPC_ADDR=":9090"

CMD ["bash"]
